name: cers
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.10
  - pip
  - pytorch
  - bitsandbytes
  - peft
  - numpy<2
  - pandas
  - scikit-learn
  - transformers
  - sentencepiece
  - protobuf
  - wandb
  - datasets
  - ipykernel
  - tqdm
  - pytables
  - torchmetrics
