name: cers
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - bitsandbytes
  - peft
  - numpy
  - pandas
  - scikit-learn
  - transformers
  - sentencepiece
  - protobuf
  - wandb
  - datasets
  - ipykernel
  - tqdm
  - pytables
  - pip:
    - flash-attn
