name: crecs
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - bitsandbytes
  - peft
  - numpy
  - pandas
  - cinemagoer
  - scikit-learn
  - transformers
  - sentence-transformers
  - sentencepiece
  - protobuf
  - optuna
  - wandb
  - datasets
  - ipykernel
  - tqdm
  - pytables
  - torchmetrics
  - flask
  - flask-cors
