name: "ml-20m ModernBERT 8k Users MNRL LR Scheduler"
random_seed: 42
batch_size: 128

model:
  recommender:
    embed_dim: 768
    mlp_dims: [768, 768]
    dropout: 0.5
    weights: NULL

  encoder:
    model_name: "answerdotai/ModernBERT-base"
    embedding_dropout: 0.2
    mlp_dropout: 0.2
    attention_dropout: 0.2


classifier:
  embed_dim: 768
  dropout: 0.0

expander:
  embed_dim: 768
  width: 2.0
  dropout: 0.5

criterion:
  triplet_scale: 20
  focal_gamma: 0.75
  vicreg_gamma: 1.0
  loss_weights:
    mse: 5.5
    id: 3.2
    triplet: 8.3
    variance: 0.9
    invariance: 0.75
    covariance: 0.45


optimizer:
  all:
    amsgrad: True
    betas: [0.9, 0.98]
    eps: 1.0e-6
  encoder:
    weight_decay: 0.05
  classifier:
    weight_decay: 0.05
  expander:
    weight_decay: 0.01
  recommender:
    weight_decay: 0.1

scheduler:
  period: 10885
  warmup_steps: 500
  restart_decay: 0.7
  min_lr:
    encoder: 1.0e-6
    classifier: 1.0e-5
    expander: 1.0e-5
    recommender: 1.0e-5
  max_lr:
    encoder: 1.0e-4
    classifier: 1.0e-4
    expander: 1.0e-4
    recommender: 1.0e-4

train:
  max_epochs: 3
  max_grad_norm: NULL