name: "ml-20m_descriptions"
training_mode: "Content"
random_seed: 42

data:
  root: "/home/tdutton/datasets/crecs/ml-20m/"
  batch_size: 128
  num_workers: 4

train:
  num_epochs: 5
  output_dir: "weights/content"

model:
  recommender:
    embed_dim: 768
    mlp_dims: [768, 768]
    dropout: 0.5
    weights: NULL

  encoder:
    model_name: "answerdotai/ModernBERT-base"
    embedding_dropout: 0.2
    mlp_dropout: 0.2
    attention_dropout: 0.2

classifier:
  embed_dim: 768
  dropout: 0.0

expander:
  embed_dim: 768
  width: 2.0
  dropout: 0.0

scheduler:
  period: 10000
  warmup_steps: 500
  restart_decay: 1.0
  min_lr:
    encoder: 1.0e-5
    classifier: 5.0e-5
    expander: 1.0e-5
    recommender: 5.0e-4
  max_lr:
    encoder: 1.0e-4
    classifier: 5.0e-4
    expander: 1.0e-4
    recommender: 5.0e-3

optimizer:
  all:
    amsgrad: True
    betas: [0.9, 0.98]
    eps: 1.0e-6
  encoder:
    weight_decay: 1.0e-2
  classifier:
    weight_decay: 1.0e-2
  expander:
    weight_decay: 1.0e-2
  recommender:
    weight_decay: 1.0e-2

criterion:
  triplet_scale: 20
  focal_gamma: 1.0
  vicreg_gamma: 1.0
  loss_weights:
    mse: 1.0
    id: 1.0
    triplet: 0.1
    variance: 0.0
    invariance: 0.0
    covariance: 0.0

evaluator:
  k:
    - 10
    - 20
  threshold: 0.6