name: "ml-20m Negative Descriptions"
random_seed: 42
batch_size: 14

encoder:
  model_name: "bert-base-uncased"
  hidden_dropout_prob: 0.0
  weights: NULL

classifier:
  dropout: 0.0

expander:
  width: 2.0
  dropout: 0.0

criterion:
  triplet_margin: 1.0 
  focal_gamma: 0.0
  vicreg_gamma: 1.0
  loss_weights:
    id: 0.1
    triplet: 10.0
    variance: 0.8
    invariance: 0.8
    covariance: 0.08

optimizer:
  encoder:
    lr: 0.000005
    weight_decay: 0.01
  classifier:
    lr: 0.0001
    weight_decay: 0.01
  expander:
    lr: 0.0001
    weight_decay: 0.01

train:
  max_epochs: 10
  accumulation_steps: 1