random_seed: 42
batch_size: 16

train:
  max_epochs: 5
  accumulation_steps: 1

loss_weights:
  id: 0.1
  triplet: 10.0
  variance: 0.8
  invariance: 0.8
  covariance: 0.08

optimizer:
  encoder:
    lr: 0.00001
    weight_decay: 0.1
  classifier:
    lr: 0.001
    weight_decay: 0.01
  expander:
    lr: 0.001
    weight_decay: 0.01

encoder:
  hidden_dropout_prob: 0.0
  weights: NULL