name: "Processed Ratings Single Rating Higher L2"
random_seed: 42
batch_size: 1024

recommender:
  embed_dim: 768
  mlp_dims: [768, 768]
  dropout: 0.9
  weights: NULL

optimizer:
  lr: 0.001
  weight_decay: 0.1
  
train:
  max_epochs: 10