name: "ml-20m_deepfm_batch-norm_larger-lr"
training_mode: "Recommender"
random_seed: 42

data:
  root: "/home/tdutton/datasets/crecs/ml-20m/"
  batch_size: 1024
  num_workers: 0

train:
  num_epochs: 3
  output_dir: "weights/recommender"

recommender:
  embed_dim: 768
  mlp_dims: [768, 768]
  dropout: 0.8
  weights: NULL

scheduler:
  period: 6000
  warmup_steps: 100
  restart_decay: 0.7
  min_lr:
    recommender: 5.0e-4
  max_lr:
    recommender: 5.0e-3

optimizer:
  weight_decay: 1.0e-2

evaluator:
  k:
    - 10
    - 20
  threshold: 0.6
