name: "LR Scheduler Faster Decay Shorter Warmup"
random_seed: 42
batch_size: 1024
data_root: "/home/tdutton/datasets/crecs/ml-20m/"

recommender:
  embed_dim: 768
  mlp_dims: [768, 768]
  dropout: 0.8
  weights: NULL

optimizer:
  lr: 1.0e-3
  weight_decay: 1.0e-2

scheduler:
  period: 6205
  warmup_steps: 100
  restart_decay: 0.7
  min_lr:
    recommender: 1.0e-4
  max_lr:
    recommender: 1.0e-3
  
train:
  num_epochs: 5

evaluator:
  k:
    - 10
    - 20
  threshold: 0.6
